export const TRUCK_VISIT_ERROR_CODES = {
  NOT_FOUND: 'TRUCK_VISIT_NOT_FOUND',
  INVALID_STATE: 'TRUCK_VISIT_INVALID_STATE',
  CANNOT_ARRIVE: 'TRUCK_VISIT_CANNOT_ARRIVE',
  CANNOT_CANCEL: 'TRUCK_VISIT_CANNOT_CANCEL',
  CONTAINER_NOT_AUTHORIZED: 'CONTAINER_NOT_AUTHORIZED',
  CONTAINER_HAS_ACTIVE_TRUCK_VISIT: 'CONTAINER_HAS_ACTIVE_TRUCK_VISIT',
  MOVEMENT_ORDER_EXPIRED_OR_MISSING: 'MOVEMENT_ORDER_EXPIRED_OR_MISSING',
  INVALID_CONTAINER_VISIT: 'INVALID_CONTAINER_VISIT',
  DUPLICATE_CONTAINER_IN_REQUEST: 'DUPLICATE_CONTAINER_IN_REQUEST',
} as const;

export type TruckVisitErrorCode =
  (typeof TRUCK_VISIT_ERROR_CODES)[keyof typeof TRUCK_VISIT_ERROR_CODES];
