export const YARD_ERROR_CODES = {
  BLOCK_NOT_FOUND: 'YARD_BLOCK_NOT_FOUND',
  SLOT_NOT_FOUND: 'YARD_SLOT_NOT_FOUND',
  BLOCK_CODE_IN_USE: 'YARD_BLOCK_CODE_IN_USE',
  SLOT_COORDINATE_IN_USE: 'YARD_SLOT_COORDINATE_IN_USE',
  VISIT_NOT_FOUND: 'YARD_CONTAINER_VISIT_NOT_FOUND',
  VISIT_NOT_IN_YARD: 'YARD_CONTAINER_NOT_IN_YARD',
  LOCATION_ALREADY_ASSIGNED: 'YARD_LOCATION_ALREADY_ASSIGNED',
  SLOT_NOT_OPERATIONAL: 'YARD_SLOT_NOT_OPERATIONAL',
  BLOCK_NOT_OPERATIONAL: 'YARD_BLOCK_NOT_OPERATIONAL',
  SLOT_OCCUPIED: 'YARD_SLOT_OCCUPIED',
  CONTAINER_TYPE_UNSUPPORTED: 'YARD_CONTAINER_TYPE_UNSUPPORTED',
  REEFER_POWER_REQUIRED: 'YARD_REEFER_POWER_REQUIRED',
  MAX_WEIGHT_EXCEEDED: 'YARD_MAX_WEIGHT_EXCEEDED',
  ASSIGNMENT_BLOCKED: 'YARD_ASSIGNMENT_BLOCKED',
  UPDATE_EMPTY: 'YARD_UPDATE_EMPTY',
} as const;

export type YardErrorCode =
  (typeof YARD_ERROR_CODES)[keyof typeof YARD_ERROR_CODES];
