export const GATE_PASS_BLOCKER_CODES = {
  CONTAINER_NOT_IN_YARD: 'CONTAINER_NOT_IN_YARD',
  NO_YARD_POSITION: 'NO_YARD_POSITION',
  NO_BILLING: 'NO_BILLING',
  BILLING_INCOMPLETE: 'BILLING_INCOMPLETE',
  BILLING_CONFIGURATION_MISSING: 'BILLING_CONFIGURATION_MISSING',
  UNBILLED_SERVICES: 'UNBILLED_SERVICES',
  ACTIVE_YARD_OPERATION: 'ACTIVE_YARD_OPERATION',
  INSPECTION_HOLD: 'INSPECTION_HOLD',
  OPERATIONAL_HOLD: 'OPERATIONAL_HOLD',
} as const;

export type GatePassBlockerCode =
  (typeof GATE_PASS_BLOCKER_CODES)[keyof typeof GATE_PASS_BLOCKER_CODES];
