export const GATE_PASS_ERROR_CODES = {
  GATE_PASS_NOT_FOUND: 'GATE_PASS_NOT_FOUND',
  GATE_PASS_NOT_READY: 'GATE_PASS_NOT_READY',
  GATE_PASS_ALREADY_EXISTS: 'GATE_PASS_ALREADY_EXISTS',
  GATE_PASS_INVALID_STATE: 'GATE_PASS_INVALID_STATE',
  GATE_PASS_EXPIRED: 'GATE_PASS_EXPIRED',
  GATE_PASS_USED: 'GATE_PASS_USED',
  CONTAINER_VISIT_NOT_FOUND: 'CONTAINER_VISIT_NOT_FOUND',
} as const;
