export const AUDIT_ACTIONS = {
  MANIFEST_CREATED: 'MANIFEST_CREATED',
  MANIFEST_UPDATED: 'MANIFEST_UPDATED',
  MANIFEST_SUBMITTED: 'MANIFEST_SUBMITTED',
  MANIFEST_CANCELLED: 'MANIFEST_CANCELLED',
  CONTAINER_CREATED: 'CONTAINER_CREATED',
  CONTAINER_UPDATED: 'CONTAINER_UPDATED',
  CONTAINER_CANCELLED: 'CONTAINER_CANCELLED',
  MOVEMENT_ORDER_CREATED: 'MOVEMENT_ORDER_CREATED',
  MOVEMENT_ORDER_AUTHORIZED: 'MOVEMENT_ORDER_AUTHORIZED',
  MOVEMENT_ORDER_CANCELLED: 'MOVEMENT_ORDER_CANCELLED',
  TRUCK_VISIT_CREATED: 'TRUCK_VISIT_CREATED',
  TRUCK_VISIT_ARRIVED: 'TRUCK_VISIT_ARRIVED',
  GATE_IN_COMPLETED: 'GATE_IN_COMPLETED',
  YARD_LOCATION_ASSIGNED: 'YARD_LOCATION_ASSIGNED',
  YARD_LOCATION_RELOCATED: 'YARD_LOCATION_RELOCATED',
  SERVICE_ORDER_CREATED: 'SERVICE_ORDER_CREATED',
  SERVICE_ORDER_CONFIRMED: 'SERVICE_ORDER_CONFIRMED',
  TARIFF_CREATED: 'TARIFF_CREATED',
  TARIFF_ACTIVATED: 'TARIFF_ACTIVATED',
  OPERATIONAL_HOLD_PLACED: 'OPERATIONAL_HOLD_PLACED',
  OPERATIONAL_HOLD_RELEASED: 'OPERATIONAL_HOLD_RELEASED',
  GATE_PASS_ISSUED: 'GATE_PASS_ISSUED',
  GATE_PASS_CANCELLED: 'GATE_PASS_CANCELLED',
  GATE_OUT_COMPLETED: 'GATE_OUT_COMPLETED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS] | string;

export const AUDIT_ENTITY_TYPES = {
  MANIFEST: 'MANIFEST',
  CONTAINER_VISIT: 'CONTAINER_VISIT',
  MOVEMENT_ORDER: 'MOVEMENT_ORDER',
  TRUCK_VISIT: 'TRUCK_VISIT',
  SERVICE_ORDER: 'SERVICE_ORDER',
  TARIFF: 'TARIFF',
  OPERATIONAL_HOLD: 'OPERATIONAL_HOLD',
  GATE_PASS: 'GATE_PASS',
} as const;

export type AuditEntityType = (typeof AUDIT_ENTITY_TYPES)[keyof typeof AUDIT_ENTITY_TYPES] | string;
