// Mirrors internal API controller permissions; the server remains authoritative.
// Regenerate with audit/tools/inventory-backend-permissions.mjs then sync-web-write-permissions.mjs.
const WRITE_ROUTES: ReadonlyArray<readonly [string, string, string | null]> = [
  [
    "POST",
    "/service-orders/preview",
    "billing.read"
  ],
  [
    "POST",
    "/containers/:visitId/service-orders",
    "billing.manage"
  ],
  [
    "POST",
    "/service-orders/:id/recalculate",
    "billing.manage"
  ],
  [
    "POST",
    "/service-orders/:id/confirm",
    "billing.manage"
  ],
  [
    "POST",
    "/service-orders/:id/cancel",
    "billing.manage"
  ],
  [
    "POST",
    "/service-orders/:serviceOrderId/invoice",
    "billing.manage"
  ],
  [
    "POST",
    "/invoices/:invoiceId/payments",
    "billing.manage"
  ],
  [
    "POST",
    "/admin/tariffs",
    "tariff.manage"
  ],
  [
    "PATCH",
    "/admin/tariffs/:id",
    "tariff.manage"
  ],
  [
    "POST",
    "/admin/tariffs/:id/rules",
    "tariff.manage"
  ],
  [
    "DELETE",
    "/admin/tariffs/:id/rules/:ruleId",
    "tariff.manage"
  ],
  [
    "POST",
    "/admin/tariffs/:id/activate",
    "tariff.manage"
  ],
  [
    "POST",
    "/admin/tariffs/:id/retire",
    "tariff.manage"
  ],
  [
    "POST",
    "/containers",
    "container.create"
  ],
  [
    "PATCH",
    "/containers/:visitId",
    "container.update"
  ],
  [
    "POST",
    "/containers/:visitId/cancel",
    "container.cancel"
  ],
  [
    "PUT",
    "/integrations/edi/routes/:shippingLineId",
    "edi.manage"
  ],
  [
    "POST",
    "/integrations/edi/outbox/:id/retry",
    "edi.manage"
  ],
  [
    "POST",
    "/integrations/edi/dispatch",
    "edi.dispatch"
  ],
  [
    "POST",
    "/integrations/edi/acks/ingest",
    "edi.ack.ingest"
  ],
  [
    "POST",
    "/integrations/edi/alerts/:id/acknowledge",
    "edi.alert.manage"
  ],
  [
    "POST",
    "/integrations/edi/alerts/:id/resolve",
    "edi.alert.manage"
  ],
  [
    "POST",
    "/integrations/edi/alerts/sync",
    "edi.alert.manage"
  ],
  [
    "POST",
    "/containers/:visitId/gate-in",
    "gate_in.create"
  ],
  [
    "POST",
    "/gate-out",
    "gate_pass.use"
  ],
  [
    "POST",
    "/containers/:visitId/gate-pass",
    "gate_pass.create"
  ],
  [
    "POST",
    "/gate-passes/:gatePassId/cancel",
    "gate_pass.create"
  ],
  [
    "POST",
    "/gate-pass/scan",
    "gate_pass.use"
  ],
  [
    "POST",
    "/manifests/:manifestId/master-bls/:mblId/house-bls",
    "manifest.update"
  ],
  [
    "PATCH",
    "/manifests/:manifestId/master-bls/:mblId/house-bls/:hblId",
    "manifest.update"
  ],
  [
    "DELETE",
    "/manifests/:manifestId/master-bls/:mblId/house-bls/:hblId",
    "manifest.update"
  ],
  [
    "POST",
    "/manifests",
    "manifest.create"
  ],
  [
    "PATCH",
    "/manifests/:manifestId",
    "manifest.update"
  ],
  [
    "POST",
    "/manifests/:manifestId/submit",
    "manifest.submit"
  ],
  [
    "POST",
    "/manifests/:manifestId/cancel",
    "manifest.cancel"
  ],
  [
    "POST",
    "/manifests/:manifestId/master-bls",
    "manifest.update"
  ],
  [
    "PATCH",
    "/manifests/:manifestId/master-bls/:mblId",
    "manifest.update"
  ],
  [
    "DELETE",
    "/manifests/:manifestId/master-bls/:mblId",
    "manifest.update"
  ],
  [
    "POST",
    "/admin/master-data/clearing-agents",
    "master_data.manage"
  ],
  [
    "PATCH",
    "/admin/master-data/clearing-agents/:id",
    "master_data.manage"
  ],
  [
    "POST",
    "/admin/master-data/clearing-agents/:id/activate",
    "master_data.manage"
  ],
  [
    "POST",
    "/admin/master-data/clearing-agents/:id/deactivate",
    "master_data.manage"
  ],
  [
    "POST",
    "/admin/master-data/consignees",
    "master_data.manage"
  ],
  [
    "PATCH",
    "/admin/master-data/consignees/:id",
    "master_data.manage"
  ],
  [
    "POST",
    "/admin/master-data/consignees/:id/activate",
    "master_data.manage"
  ],
  [
    "POST",
    "/admin/master-data/consignees/:id/deactivate",
    "master_data.manage"
  ],
  [
    "POST",
    "/admin/master-data/:type",
    "master_data.manage"
  ],
  [
    "PATCH",
    "/admin/master-data/:type/:id",
    "master_data.manage"
  ],
  [
    "POST",
    "/admin/master-data/shipping-lines",
    "master_data.manage"
  ],
  [
    "PATCH",
    "/admin/master-data/shipping-lines/:id",
    "master_data.manage"
  ],
  [
    "POST",
    "/admin/master-data/shipping-lines/:id/activate",
    "master_data.manage"
  ],
  [
    "POST",
    "/admin/master-data/shipping-lines/:id/deactivate",
    "master_data.manage"
  ],
  [
    "POST",
    "/admin/master-data/transporters",
    "master_data.manage"
  ],
  [
    "PATCH",
    "/admin/master-data/transporters/:id",
    "master_data.manage"
  ],
  [
    "POST",
    "/admin/master-data/transporters/:id/activate",
    "master_data.manage"
  ],
  [
    "POST",
    "/admin/master-data/transporters/:id/deactivate",
    "master_data.manage"
  ],
  [
    "POST",
    "/containers/:visitId/movement-orders",
    "movement_order.create"
  ],
  [
    "PATCH",
    "/movement-orders/:orderId",
    "movement_order.update"
  ],
  [
    "POST",
    "/movement-orders/:orderId/authorize",
    "movement_order.authorize"
  ],
  [
    "POST",
    "/movement-orders/:orderId/cancel",
    "movement_order.cancel"
  ],
  [
    "POST",
    "/containers/:visitId/holds",
    "operational_hold.manage"
  ],
  [
    "POST",
    "/containers/:visitId/holds/:holdId/release",
    "operational_hold.manage"
  ],
  [
    "POST",
    "/customer-warehouses",
    "master_data.manage"
  ],
  [
    "PATCH",
    "/customer-warehouses/:id",
    "master_data.manage"
  ],
  [
    "POST",
    "/admin/partner-clients",
    "partner_client.manage"
  ],
  [
    "POST",
    "/admin/partner-clients/:id/rotate",
    "partner_client.manage"
  ],
  [
    "POST",
    "/admin/partner-clients/:id/revoke",
    "partner_client.manage"
  ],
  [
    "POST",
    "/handovers",
    "handover.create"
  ],
  [
    "POST",
    "/handovers/:id/publish",
    "handover.create"
  ],
  [
    "POST",
    "/handovers/:id/icd-confirm",
    "handover.confirm"
  ],
  [
    "POST",
    "/handovers/:id/dispute",
    "handover.dispute"
  ],
  [
    "POST",
    "/admin/roles",
    "roles.manage"
  ],
  [
    "PATCH",
    "/admin/roles/:roleId",
    "roles.manage"
  ],
  [
    "PUT",
    "/admin/roles/:roleId/permissions",
    "roles.manage"
  ],
  [
    "PATCH",
    "/admin/settings/:key",
    "settings.manage"
  ],
  [
    "POST",
    "/gate/truck-visits",
    "truck_visit.create"
  ],
  [
    "POST",
    "/gate/truck-visits/:visitId/arrive",
    "truck_visit.arrive"
  ],
  [
    "POST",
    "/gate/truck-visits/:visitId/cancel",
    "truck_visit.cancel"
  ],
  [
    "POST",
    "/admin/users",
    "users.manage"
  ],
  [
    "PATCH",
    "/admin/users/:userId",
    "users.manage"
  ],
  [
    "POST",
    "/admin/users/:userId/activate",
    "users.manage"
  ],
  [
    "POST",
    "/admin/users/:userId/deactivate",
    "users.manage"
  ],
  [
    "PUT",
    "/admin/users/:userId/roles",
    "users.manage"
  ],
  [
    "PUT",
    "/admin/users/:userId/password",
    "users.manage"
  ],
  [
    "POST",
    "/yard/blocks",
    "yard.configure"
  ],
  [
    "PATCH",
    "/yard/blocks/:blockId",
    "yard.configure"
  ],
  [
    "POST",
    "/yard/blocks/:blockId/slots",
    "yard.configure"
  ],
  [
    "PATCH",
    "/yard/slots/:slotId",
    "yard.configure"
  ],
  [
    "POST",
    "/containers/:visitId/yard/check",
    "yard.update"
  ],
  [
    "POST",
    "/containers/:visitId/yard/assign",
    "yard.update"
  ],
  [
    "POST",
    "/containers/:visitId/yard/movements",
    "yard.move"
  ],
  [
    "POST",
    "/yard/movements/:id/start",
    "yard.move"
  ],
  [
    "POST",
    "/yard/movements/:id/complete",
    "yard.move"
  ],
  [
    "POST",
    "/yard/movements/:id/cancel",
    "yard.move"
  ],
  [
    "POST",
    "/containers/:visitId/inspections",
    "yard.inspect"
  ],
  [
    "POST",
    "/inspections/:id/start",
    "yard.inspect"
  ],
  [
    "POST",
    "/inspections/:id/complete",
    "yard.inspect"
  ],
  [
    "POST",
    "/inspections/:id/cancel",
    "yard.inspect"
  ],
  [
    "POST",
    "/containers/:visitId/yard-bookings",
    "yard.booking"
  ],
  [
    "POST",
    "/yard/bookings/:id/start",
    "yard.booking"
  ],
  [
    "POST",
    "/yard/bookings/:id/complete",
    "yard.booking"
  ],
  [
    "POST",
    "/yard/bookings/:id/cancel",
    "yard.booking"
  ],
  [
    "PATCH",
    "/notifications/:id/read",
    null
  ],
  [
    "POST",
    "/notifications/read-all",
    null
  ]
];
const rules = WRITE_ROUTES.map(([method, route, permission]) => ({ method, permission,
  pattern: new RegExp('^' + route.replace(/:[^/]+/g, '[^/]+') + '$') }));
/** null: authenticated self-service route; undefined: unknown/unsupported route. */
export function requiredWritePermission(path: string, method = 'POST'): string | null | undefined {
  return rules.find(rule => rule.method === method && rule.pattern.test(path))?.permission;
}
