import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createRequire } from 'node:module';
import { JSDOM } from './node_modules/jsdom/lib/api.js';
import { Header } from '../../../apps/web/src/components/Header.tsx';
import { AppContext } from '../../../apps/web/src/context/app-context.shared.ts';
const require = createRequire(new URL('../../../apps/web/package.json', import.meta.url));
const React = require('react');
test('nonmodal notifications close on Escape, outside click, explicit close and route change', async () => {
  const dom = new JSDOM('<body><div id="host"></div><button id="outside">Outside</button></body>', { url: 'http://localhost' });
  for (const key of ['window','document','Node','HTMLElement','KeyboardEvent','MouseEvent']) globalThis[key] = dom.window[key];
  globalThis.IS_REACT_ACT_ENVIRONMENT = true;
  const { createRoot } = require('react-dom/client');
  const root = createRoot(document.getElementById('host'));
  const value = { currentUser: { id:'u',name:'Test',role:'ADMIN' },containerVisits:[],holds:[],notifications:[],refreshData:async()=>{},logout:async()=>{},isLoading:false,apiReady:true };
  const render = tab => root.render(React.createElement(AppContext.Provider,{value},React.createElement(Header,{ currentTab:tab,onMenuClick:()=>{} })));
  await React.act(async()=>render('dashboard'));
  const trigger = document.querySelector('[aria-label^="Thông báo"]');
  const open = async()=>React.act(async()=>trigger.click());
  await open();
  assert.ok(document.querySelector('[aria-label="Đóng thông báo"]'));
  await React.act(async()=>document.dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'Escape',bubbles:true})));
  assert.equal(trigger.getAttribute('aria-expanded'),'false');
  assert.equal(document.activeElement,trigger);
  await open();
  await React.act(async()=>document.getElementById('outside').dispatchEvent(new dom.window.MouseEvent('pointerdown',{bubbles:true})));
  assert.equal(trigger.getAttribute('aria-expanded'),'false');
  await open();
  await React.act(async()=>document.querySelector('[aria-label="Đóng thông báo"]').click());
  assert.equal(trigger.getAttribute('aria-expanded'),'false');
  await open();
  await React.act(async()=>render('containers'));
  assert.equal(trigger.getAttribute('aria-expanded'),'false');
  await React.act(async()=>root.unmount());
  dom.window.close();
});
