export const MANIFEST_ERROR_CODES = {
  NOT_FOUND:
    'MANIFEST_NOT_FOUND',

  INVALID_STATE:
    'MANIFEST_INVALID_STATE',

  SHIPPING_LINE_INVALID:
    'MANIFEST_SHIPPING_LINE_INVALID',

  MBL_NOT_FOUND:
    'MASTER_BL_NOT_FOUND',

  MBL_NUMBER_IN_USE:
    'MASTER_BL_NUMBER_IN_USE',

  MBL_HAS_HOUSE_BLS:
    'MASTER_BL_HAS_HOUSE_BLS',

  HBL_NOT_FOUND:
    'HOUSE_BL_NOT_FOUND',

  HBL_NUMBER_IN_USE:
    'HOUSE_BL_NUMBER_IN_USE',

  CONSIGNEE_INVALID:
    'HOUSE_BL_CONSIGNEE_INVALID',

  CLEARING_AGENT_INVALID:
    'HOUSE_BL_CLEARING_AGENT_INVALID',

  UPDATE_EMPTY:
    'MANIFEST_UPDATE_EMPTY',
} as const;
