export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',

  TOKEN_MISSING: 'AUTH_TOKEN_MISSING',

  TOKEN_INVALID: 'AUTH_TOKEN_INVALID',

  SESSION_INVALID: 'AUTH_SESSION_INVALID',

  USER_INACTIVE: 'AUTH_USER_INACTIVE',

  PERMISSION_DENIED: 'AUTH_PERMISSION_DENIED',
} as const;
