export const ROLE_ERROR_CODES = {
  NOT_FOUND: 'ROLE_NOT_FOUND',

  CODE_IN_USE: 'ROLE_CODE_IN_USE',

  UPDATE_EMPTY: 'ROLE_UPDATE_EMPTY',

  PERMISSION_INVALID: 'ROLE_PERMISSION_INVALID',

  SYSTEM_ROLE_PROTECTED: 'SYSTEM_ROLE_PROTECTED',
} as const;
