export const MOVEMENT_ORDER_ERROR_CODES = {
  NOT_FOUND: 'MOVEMENT_ORDER_NOT_FOUND',
  CONTAINER_VISIT_NOT_FOUND: 'CONTAINER_VISIT_NOT_FOUND',
  CONTAINER_VISIT_INVALID_STATE: 'CONTAINER_VISIT_INVALID_STATE',
  ACTIVE_ORDER_EXISTS: 'MOVEMENT_ORDER_ACTIVE_ORDER_EXISTS',
  NOT_DRAFT: 'MOVEMENT_ORDER_NOT_DRAFT',
  ORDER_EXPIRED: 'MOVEMENT_ORDER_EXPIRED',
  MANIFEST_NOT_SUBMITTED: 'MOVEMENT_ORDER_MANIFEST_NOT_SUBMITTED',
  EXPIRES_AT_MUST_BE_FUTURE: 'MOVEMENT_ORDER_EXPIRES_AT_MUST_BE_FUTURE',
} as const;

export type MovementOrderErrorCode =
  (typeof MOVEMENT_ORDER_ERROR_CODES)[keyof typeof MOVEMENT_ORDER_ERROR_CODES];
