export const EDI_ERROR_CODES = {
  EDI_ROUTE_NOT_FOUND: 'EDI_ROUTE_NOT_FOUND',
  EDI_ROUTE_DISABLED: 'EDI_ROUTE_DISABLED',
  EDI_OUTBOX_NOT_FOUND: 'EDI_OUTBOX_NOT_FOUND',
  EDI_OUTBOX_INVALID_STATE: 'EDI_OUTBOX_INVALID_STATE',
  EDI_CREDENTIAL_MISSING: 'EDI_CREDENTIAL_MISSING',
  EDI_TRANSPORT_FAILED: 'EDI_TRANSPORT_FAILED',
  SHIPPING_LINE_NOT_FOUND: 'SHIPPING_LINE_NOT_FOUND',
} as const;
