export const MASTER_DATA_ERROR_CODES = {
  NOT_FOUND:
    'MASTER_DATA_NOT_FOUND',

  IDENTIFIER_IN_USE:
    'MASTER_DATA_IDENTIFIER_IN_USE',

  UPDATE_EMPTY:
    'MASTER_DATA_UPDATE_EMPTY',
} as const;
