export const BILLING_SOURCE_TYPES = {
  CONTAINER_RECEPTION: 'CONTAINER_RECEPTION',
  STORAGE_PERIOD: 'STORAGE_PERIOD',
  IN_YARD_BOOKING: 'IN_YARD_BOOKING',
  CONTAINER_INSPECTION: 'CONTAINER_INSPECTION',
  YARD_MOVEMENT: 'YARD_MOVEMENT',
} as const;

export type BillingSourceType = (typeof BILLING_SOURCE_TYPES)[keyof typeof BILLING_SOURCE_TYPES];
