export const BILLING_ERROR_CODES = {
  TARIFF_NOT_FOUND: 'TARIFF_NOT_FOUND',
  TARIFF_RULE_NOT_FOUND: 'TARIFF_RULE_NOT_FOUND',
  TARIFF_INVALID_STATE: 'TARIFF_INVALID_STATE',
  TARIFF_RULE_DUPLICATE: 'TARIFF_RULE_DUPLICATE',
  TARIFF_GENERIC_RULE_MISSING: 'TARIFF_GENERIC_RULE_MISSING',
  TARIFF_EFFECTIVE_RANGE_INVALID: 'TARIFF_EFFECTIVE_RANGE_INVALID',
  BILLING_CONFIGURATION_MISSING: 'BILLING_CONFIGURATION_MISSING',
  SERVICE_TYPE_INVALID: 'BILLING_SERVICE_TYPE_INVALID',
  CONTAINER_NOT_BILLABLE: 'BILLING_CONTAINER_NOT_BILLABLE',
  CONSIGNEE_REQUIRED: 'BILLING_CONSIGNEE_REQUIRED',
  DRAFT_ORDER_EXISTS: 'BILLING_DRAFT_ORDER_EXISTS',
  PREVIOUS_ORDER_PENDING_INVOICE: 'BILLING_PREVIOUS_ORDER_PENDING_INVOICE',
  NO_UNBILLED_SERVICES: 'BILLING_NO_UNBILLED_SERVICES',
  SERVICE_ORDER_NOT_FOUND: 'SERVICE_ORDER_NOT_FOUND',
  SERVICE_ORDER_INVALID_STATE: 'SERVICE_ORDER_INVALID_STATE',
  SERVICE_ORDER_EMPTY: 'SERVICE_ORDER_EMPTY',
} as const;

export type BillingErrorCode =
  (typeof BILLING_ERROR_CODES)[keyof typeof BILLING_ERROR_CODES];
