export const PARTNER_CLIENT_SCOPES = {
  HANDOVERS_READ: 'handovers:read',
  HANDOVERS_ACCEPT: 'handovers:accept',
  HANDOVERS_IN_TRANSIT: 'handovers:in_transit',
  HANDOVERS_CONFIRM: 'handovers:confirm',
  HANDOVERS_DISPUTE: 'handovers:dispute',
  CONTAINERS_READ: 'containers:read',
} as const;

export type PartnerClientScope =
  (typeof PARTNER_CLIENT_SCOPES)[keyof typeof PARTNER_CLIENT_SCOPES];

export const ALL_PARTNER_SCOPES: PartnerClientScope[] = [
  PARTNER_CLIENT_SCOPES.HANDOVERS_READ,
  PARTNER_CLIENT_SCOPES.HANDOVERS_ACCEPT,
  PARTNER_CLIENT_SCOPES.HANDOVERS_IN_TRANSIT,
  PARTNER_CLIENT_SCOPES.HANDOVERS_CONFIRM,
  PARTNER_CLIENT_SCOPES.HANDOVERS_DISPUTE,
  PARTNER_CLIENT_SCOPES.CONTAINERS_READ,
];

export const PARTNER_HANDOVER_ERROR_CODES = {
  HANDOVER_NOT_FOUND: 'HANDOVER_NOT_FOUND',
  HANDOVER_INVALID_STATE: 'HANDOVER_INVALID_STATE',
  HANDOVER_CONFIRMATION_MISSING: 'HANDOVER_CONFIRMATION_MISSING',
  HANDOVER_ALREADY_COMPLETED: 'HANDOVER_ALREADY_COMPLETED',
  HANDOVER_DISPUTE_REASON_REQUIRED: 'HANDOVER_DISPUTE_REASON_REQUIRED',
  HANDOVER_REJECT_REASON_REQUIRED: 'HANDOVER_REJECT_REASON_REQUIRED',
  HANDOVER_DELIVERY_FAILURE_INVALID_TIME:
    'HANDOVER_DELIVERY_FAILURE_INVALID_TIME',
  HANDOVER_WAREHOUSE_CONFIRMATION_INVALID:
    'HANDOVER_WAREHOUSE_CONFIRMATION_INVALID',
  HANDOVER_REVIEW_FAILED: 'HANDOVER_REVIEW_FAILED',
} as const;


