export const PARTNER_CLIENT_SCOPES = {
  HANDOVERS_READ: 'handovers:read',
  HANDOVERS_ACCEPT: 'handovers:accept',
  HANDOVERS_IN_TRANSIT: 'handovers:in_transit',
  HANDOVERS_CONFIRM: 'handovers:confirm',
  HANDOVERS_DISPUTE: 'handovers:dispute',
  CONTAINERS_READ: 'containers:read',
} as const;

export type PartnerClientScope =
  (typeof PARTNER_CLIENT_SCOPES)[keyof typeof PARTNER_CLIENT_SCOPES];

export const ALL_PARTNER_SCOPES: PartnerClientScope[] = [
  PARTNER_CLIENT_SCOPES.HANDOVERS_READ,
  PARTNER_CLIENT_SCOPES.HANDOVERS_ACCEPT,
  PARTNER_CLIENT_SCOPES.HANDOVERS_IN_TRANSIT,
  PARTNER_CLIENT_SCOPES.HANDOVERS_CONFIRM,
  PARTNER_CLIENT_SCOPES.HANDOVERS_DISPUTE,
  PARTNER_CLIENT_SCOPES.CONTAINERS_READ,
];
