export const CONTAINER_EVENT_TYPES = {
  VISIT_CREATED: 'VISIT_CREATED',
  VISIT_UPDATED: 'VISIT_UPDATED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  VISIT_CANCELLED: 'VISIT_CANCELLED',
  MOVEMENT_ORDER_CREATED: 'MOVEMENT_ORDER_CREATED',
  MOVEMENT_ORDER_UPDATED: 'MOVEMENT_ORDER_UPDATED',
  MOVEMENT_AUTHORIZED: 'MOVEMENT_AUTHORIZED',
  MOVEMENT_ORDER_CANCELLED: 'MOVEMENT_ORDER_CANCELLED',
  MOVEMENT_ORDER_EXPIRED: 'MOVEMENT_ORDER_EXPIRED',
  TRUCK_VISIT_SCHEDULED: 'TRUCK_VISIT_SCHEDULED',
  TRUCK_VISIT_ARRIVED: 'TRUCK_VISIT_ARRIVED',
  TRUCK_VISIT_CANCELLED: 'TRUCK_VISIT_CANCELLED',
  HOLD_APPLIED: 'HOLD_APPLIED',
  HOLD_RELEASED: 'HOLD_RELEASED',
  GATE_IN: 'GATE_IN',
  GATE_IN_SEAL_MISMATCH: 'GATE_IN_SEAL_MISMATCH',
  YARD_MOVED: 'YARD_MOVED',
  INSPECTION_COMPLETED: 'INSPECTION_COMPLETED',
  GATE_OUT: 'GATE_OUT',
} as const;

export type ContainerEventType =
  (typeof CONTAINER_EVENT_TYPES)[keyof typeof CONTAINER_EVENT_TYPES];

