export const CONTAINER_EVENT_TYPES = {
  VISIT_CREATED: 'VISIT_CREATED',
  VISIT_UPDATED: 'VISIT_UPDATED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  VISIT_CANCELLED: 'VISIT_CANCELLED',
  HOLD_APPLIED: 'HOLD_APPLIED',
  HOLD_RELEASED: 'HOLD_RELEASED',
  GATE_IN: 'GATE_IN',
  YARD_MOVED: 'YARD_MOVED',
  INSPECTION_COMPLETED: 'INSPECTION_COMPLETED',
  GATE_OUT: 'GATE_OUT',
} as const;

export type ContainerEventType =
  (typeof CONTAINER_EVENT_TYPES)[keyof typeof CONTAINER_EVENT_TYPES];
