export const CONTAINER_ERROR_CODES = {
  NOT_FOUND: 'CONTAINER_NOT_FOUND',
  VISIT_NOT_FOUND: 'CONTAINER_VISIT_NOT_FOUND',
  INVALID_ISO_NUMBER: 'CONTAINER_INVALID_ISO_NUMBER',
  ACTIVE_VISIT_EXISTS: 'CONTAINER_ACTIVE_VISIT_EXISTS',
  HOUSE_BL_NOT_FOUND: 'CONTAINER_HOUSE_BL_NOT_FOUND',
  INVALID_STATUS_TRANSITION: 'CONTAINER_INVALID_STATUS_TRANSITION',
  UPDATE_NOT_ALLOWED: 'CONTAINER_UPDATE_NOT_ALLOWED',
  CANCEL_NOT_ALLOWED: 'CONTAINER_CANCEL_NOT_ALLOWED',
  HOLD_STATUS_RESTRICTED: 'CONTAINER_HOLD_STATUS_RESTRICTED',
} as const;

export type ContainerErrorCode =
  (typeof CONTAINER_ERROR_CODES)[keyof typeof CONTAINER_ERROR_CODES];
